### ISSUE TITLE
Installer froze during root.img extraction

### ISSUE THREAD

**Issue by abarisain** [AsahiLinux/asahi-installer#36]
Hi,
Super pumped to be able to give Asahi a shot :) Congrats on the release!

I've attempted the installer today (M1 Pro), and I got stuck on
```
Extracting root.img into disk0s7 partition
++++++++++++++++++++++++++
```

I had to kill it, as it stopped progressing even after 10 minutes and I could not see any I/O activity (no disk, no network). 

I'm pretty sure that my macbook went to sleep during that step, as my display is set to turn off after two minutes on battery. Restarting the process with Amphetamine inhibiting sleep worked fine. 

If that's not already the case, may I suggest that the installer inhibits sleep during critical steps, or at least warns about sleep settings? That's, of course, assuming that my theory about how it got stuck is right.

Sidebar: Recovering from that incomplete state wasn't straightforward (but easy using some diskutil eraseVolume), but it's another subject and I didn't expect the installer to be able to do so. No biggie.

**Comment by moham96** [comment]
faced the same issue, killed it, and retried again but I can't choose the previously created Linux partition, tried to delete the partition from the disk utility but I can't see it there, please help

**Comment by abarisain** [comment]
you need to use the diskutil CLI to erase the volumes and start again.

Be very careful as you can break your system that way.

**Comment by moham96** [comment]
@abarisain  can you provide more info?
My partition layout is this right now:

```
rhx@MOHAMMADs-Air ~ % diskutil list
/dev/disk0 (internal):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      GUID_partition_scheme                         251.0 GB   disk0
   1:             Apple_APFS_ISC                         524.3 MB   disk0s1
   2:                 Apple_APFS Container disk3         230.0 GB   disk0s2
   3:                 Apple_APFS Container disk4         2.5 GB     disk0s5
   4:                        EFI EFI - ASAHI             500.2 MB   disk0s4
   5:           Linux Filesystem                         12.1 GB    disk0s7
   6:        Apple_APFS_Recovery                         5.4 GB     disk0s3

/dev/disk3 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +230.0 GB   disk3
                                 Physical Store disk0s2
   1:                APFS Volume Macintosh HD            15.2 GB    disk3s1
   2:              APFS Snapshot com.apple.os.update-... 15.2 GB    disk3s1s1
   3:                APFS Volume Preboot                 475.1 MB   disk3s2
   4:                APFS Volume Recovery                798.2 MB   disk3s3
   5:                APFS Volume Data                    130.3 GB   disk3s5
   6:                APFS Volume VM                      20.5 KB    disk3s6

/dev/disk4 (synthesized):
   #:                       TYPE NAME                    SIZE       IDENTIFIER
   0:      APFS Container Scheme -                      +2.5 GB     disk4
                                 Physical Store disk0s5
```
I tried to merge the newly created partitions with `diskutil mergePartitions APFS linux /dev/disk0s4 /dev/disk0s7` but it says It couldn't read partition map

can you provide the commands you executed to remove the partitions so i can adjust them based on my layout?

**Comment by moham96** [comment]
nevermind, i had to run `diskutil apfs deleteContainer disk1` then deleted the efi and the linux volumes
now I will try to install asahi again

**Comment by marcan** [comment]
This issue should be fixed in the latest installer (v0.3.11), which properly sets up download timeouts.

**Comment by krestaino** [comment]
[moham96](https://github.com/moham96), could you list out which commands you used to recover from the state you were in? I'm stuck in the same boat and I'm not familiar with diskutil and don't want to nuke my macOS partition by mistake.

**Comment by Mraghuvaran** [comment]
@moham96  . Please also help me to clean my drives .. I'll have to reinstall again

**Comment by moham96** [comment]
@Mraghuvaran reboot then post the output of `diskutil list`

**Comment by Mraghuvaran** [comment]
Step 1: diskutil list  output 

<img width="1358" alt="Screen Shot 2022-03-21 at 1 09 30 PM" src="https://user-images.githubusercontent.com/53115668/159221026-0ed41009-54a5-41ed-b69b-a9c0d6aa987b.png">

Step 2 : Outof Curiosity I have delted disk4 & this is the output 
<img width="1440" alt="Screen Shot 2022-03-21 at 1 10 39 PM" src="https://user-images.githubusercontent.com/53115668/159221012-abb3a33f-ab5b-400d-a765-8cad4852866e.png">

**Comment by leifliddy** [comment]
Can you just run the following script?

https://github.com/AsahiLinux/asahi-installer/blob/main/tools/wipe-linux.sh

**Comment by Mraghuvaran** [comment]
@leifliddy  Should I run the script in recovery mode?

**Comment by moham96** [comment]
@Mraghuvaran deleting disk4 is correct now you need to delete the two remaining partitions
so run 
`diskutil eraseVolume free n /dev/disk0s4`
`diskutil eraseVolume free n /dev/disk0s7`
then you can re-run the installer and choose install in free space

**Comment by leifliddy** [comment]
That script was created for that explicit purpose. IMO, it's much easier + convenient + less prone to error to run that - then it is to do it manually. It's probably best to run it from recovery just to be safe. During my testing over the last few weeks, there were multiple instances where one of the Volumes couldn't be deleted from a normal boot sesson.

I would boot to recovery, open a terminal, and run:
```curl https://raw.githubusercontent.com/AsahiLinux/asahi-installer/main/tools/wipe-linux.sh | sh```

**Comment by marcan** [comment]
FYI there is a short link at `curl -L https://alx.sh/wipe-linux`.

**Comment by abarisain** [comment]
I was aware of that script but didn't expect it to work in that interrupted state. Glad it does!

The installer seems to detect properly that an installation is incomplete, as it said so on my partation list, but still asked me if I wanted to resize macOS. Maybe it could tell the user about this script on incomplete installations?

**Comment by leifliddy** [comment]
@abarisain It's funny because you said 
```
you need to use the diskutil CLI to erase the volumes and start again.
```
But that's exactly what the script is doing ; )

**Comment by abarisain** [comment]
Oh sorry, I meant I knew the script existed but didn't open it and check what was inside. If I did I would have run it.

**Comment by marcan** [comment]
The original root.img issue should be fixed by now; see #84 for uninstall information.

**Comment by Komodo640** [comment]
still having this issue, M2 Macbook Air 2022 with Sonoma, always gets stuck at around 30-35%
